# https://github.com/Un1Gfn/avx/blob/master/.circleci/config.yml

# /exp01/config.yml
# /exp02/config.yml
# /.circleci/config.yml

version: 2

jobs:

  build:

    # https://circleci.com/docs/2.0/configuration-reference/#branches
    branches:
      only:
        - xenial-aosp
        # - placeholder

    # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
    # Xenial Xerus
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false

    resource_class: medium

    steps:

      - run:
          name: "BASH_ENV"
          command: |
            cat <<"EOF" >"$BASH_ENV"
            #
            export apt="sudo -i apt-get -q --allow-downgrades --allow-remove-essential --allow-change-held-packages --allow-unauthenticated"
            # export apt="sudo -i apt-get -q --allow-downgrades --allow-remove-essential --allow-change-held-packages"
            #
            export PROJ_DIR="/root/project"
            export _JAVA_OPTIONS="-Xmx$RAM"
            #
            EOF
            source "$BASH_ENV"

      - run:
          name: "[M] Wait for SSH"
          command: |
            echo
            i=0
            while true; do
              sleep 60
              i=$((i+1))
              echo "$i min"
            done
            /usr/bin/false

      # https://packages.ubuntu.com/
      # git repo time inetutils rxvt-unicode-terminfo openssh sudo
      # wget tree nano vim pv xz unzip
      # https://source.android.com/setup/build/initializing#installing-required-packages-ubuntu-1404
      # https://android.googlesource.com/platform/build/+/master/tools/docker/Dockerfile
      - run:
          name: "apt"
          command: |
            sudo -i apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
            sudo -i apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5DC22404A6F9F1CA
            $apt update
            $apt purge  openjdk-8-jdk openjdk-8-jre openjdk-8-jre-headless
            $apt autoremove --purge
            cat <<"EOF" | xargs $apt install
            tree duc
            git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip
            EOF

      - run:
          name: "Make sure there is no J*"
          command: |
            [ -z "$(dpkg -l|grep -e jdk -e jre -e headless -e java[^s])" ] || echo "err"

      # - run:
      #     name: "Verify J*8"
      #     command: |
      #       # ?

      # https://superuser.com/questions/603547/how-can-i-limit-the-size-of-the-android-source-i-need-to-download-with-repo-syn
      # https://source.android.com/setup/develop/repo
      # wall clock time - ??:??.?? # ??GiB # aosp
      - run:
          name: "Download"
          command: |
            echo
            sudo -i df -h
            echo
            cat <<"EOF" | $chroot_bash
            pwd
            echo
            df -h
            echo
            mkdir -p /lineage
            cd /lineage
            for i in system global; do
              git config --$i user.email "darren19970810@gmail.com"
              git config --$i user.name "Darren Ng"
            done
            echo
            yes | repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-15.1
            echo
            /usr/bin/time --format="\n  wall clock time - %E\n" repo sync -c
            echo
            du -hd 0 .repo
            echo
            df -h
            echo
            source build/envsetup.sh
            EOF

      # - run:
      #     name: "Free up space"
      #     command: |
      #       df
      #       du
      #       https://www.google.com/search?q=apt+clean+cache&oq=apt+clean+cache
      #       $pkg purge
      #       rm -rf .repo
      #       rm -rf /usr/local

      # - run:
      #     name: "Build"
      #     command: |
      #       source build/envsetup.sh
      #       lunch

      # - run:
      #     name: "[M] Stop"
      #     command: |
      #       /usr/bin/false

      # - checkout # github -> /root/project

      # https://circleci.com/docs/2.0/artifacts/#artifacts-overview
      # - store_artifacts:
      #     path: /nproc
      # - store_artifacts:
      #     path: /lscpu
