# https://github.com/Un1Gfn/avx/blob/master/.circleci/config.yml

version: 2

jobs:

  build:

    # https://circleci.com/docs/2.0/configuration-reference/#branches
    branches:
      only:
        - download
        - build-A
        - build-B
        # - placeholder

    # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
    # Xenial Xerus
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false

    resource_class: medium

    steps:

      - run:
          name: "Remove bloat"
          working_directory: /opt/
          command: |
            sudo rm -rf firefox
            sudo rm -rf google/chrome
            sudo rmdir google
            sudo rm -rf circleci/.nvm
            sudo rm -rf circleci/.rvm
            sudo rm -rf circleci/.pyenv
            sudo rmdir circleci
            sudo rm -rf containerd

      - run:
          name: "BASH_ENV"
          command: |
            cat <<"EOF" >"$BASH_ENV"
            #
            export apt="sudo -i apt-get -q --allow-downgrades --allow-remove-essential --allow-change-held-packages --allow-unauthenticated"
            # export apt="sudo -i apt-get -q --allow-downgrades --allow-remove-essential --allow-change-held-packages"
            #
            # export _JAVA_OPTIONS="-Xmx$RAM"
            #
            EOF
            source "$BASH_ENV"

      # https://packages.ubuntu.com/
      # git repo time inetutils rxvt-unicode-terminfo openssh sudo
      # wget tree nano vim pv xz unzip
      # https://source.android.com/setup/build/initializing#installing-required-packages-ubuntu-1404
      # https://android.googlesource.com/platform/build/+/master/tools/docker/Dockerfile
      - run:
          name: "apt"
          command: |
            sudo -i apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
            sudo -i apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5DC22404A6F9F1CA
            $apt update
            $apt autoremove --purge
            cat <<"EOF" | xargs $apt install
            zstd
            tree duc vim
            git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip
            EOF

      - run:
          name: "Verify J*8"
          command: |
            dpkg -l | grep openjdk-8-jdk
            javac -version |& grep -F '1.8.'
            [ "$(java -version |& grep -F '1.8.' | wc -l)" -eq 2 ]

      - run:
          name: "Kill python3 and keep python 2"
          command: |
            for py in \
              {lib,}python3{,.5}{,-stdlib,-minimal}
            do
              $apt purge "$py" || true
            done
            $apt autoremove --purge
            python2 --version |& grep -Fe 'Python 2.7'
            python  --version |& grep -Fe 'Python 2.7'
            ! sh -c "python3 --version"
            [ -z "$(dpkg -l | grep python3)" ]

      - run:
          name: "[A] Disk usage (approx 5G)"
          command: |
            echo
            sudo -i df -h
            echo
            echo

      - restore_cache:
          key: v1-tree-

      - run:
          name: "[B] Disk usage (approx 5G+15G)"
          command: |
            echo
            sudo -i df -h
            echo
            echo

      - run:
          name: "Extract and drop zstd"
          working_directory: /home/circleci/
          no_output_timeout: 1h
          command: |
            ls -lh aosp.tar.zst
            zstdcat aosp.tar.zst | tar xf -
            rm -v aosp.tar.zst

      - run:
          name: "[C] Disk usage (approx 5G+30G)"
          command: |
            echo
            sudo -i df -h
            echo
            echo

      # https://source.android.com/setup/build/requirements#binaries
      # https://source.android.com/setup/build/downloading#obtaining-proprietary-binaries
      # https://developers.google.com/android/drivers#angleropm7.181205.001
      - run:
          name: "proprietary binaries"
          working_directory: /home/circleci/aosp/
          command: |
            curl -sS -LOJR https://dl.google.com/dl/android/aosp/huawei-angler-opm7.181205.001-52ed73ce.tgz
            curl -sS -LOJR https://dl.google.com/dl/android/aosp/qcom-angler-opm7.181205.001-d20950d9.tgz
            cat <<"---" | sha256sum --strict -c -
              2eb9a77de059739d33c7fad07e34034f03a93d70eea39460bb0d9278e5763053  huawei-angler-opm7.181205.001-52ed73ce.tgz
              78222d6c627020d8312477f647253b37569882ebdfe527207f39074dc05fc6a1  qcom-angler-opm7.181205.001-d20950d9.tgz
            ---
            tar xfv huawei-angler-opm*.tgz
            tar xfv qcom-angler-opm*.tgz
            rm -v huawei-angler-opm*.tgz
            rm -v qcom-angler-opm*.tgz
            PATH0="$PATH"
            PATH="$PWD:$PATH"
            ln -sv /bin/cat more
            hash -r
            type more
            file $(which more)
            echo -ne "\nI ACCEPT\n" | ./extract-huawei-angler.sh
            echo -ne "\nI ACCEPT\n" | ./extract-qcom-angler.sh
            rm -v extract-huawei-angler.sh
            rm -v extract-qcom-angler.sh
            rm -v more
            PATH="$PATH0"
            unset -v PATH0
            hash -r

      # https://source.android.com/setup/build/running#selecting-device-build
      - run:
          name: "Build-A"
          working_directory: /home/circleci/aosp/
          command: |
            cat <<"---" >./m.sh
            #!/bin/bash
            source build/envsetup.sh
            lunch aosp_angler-userdebug
            m droid
            ---
            chmod +x m.sh
            # /usr/bin/timeout "$((3*60+30))m" ./m.sh || true
            /usr/bin/timeout "$((10*1))m" ./m.sh || true

      - run:
          name: "[C] Disk space"
          command: |
            echo
            sudo -i df -h
            echo
            echo

      - run:
          name: "Pack incomplete zstd"
          working_directory: /home/circleci/
          no_output_timeout: 1h
          command: |
            tar cf - aosp/ | zstd >aosp.tar.zst
            # zstdcat aosp.tar.zst | tar xf -
            ls -lh aosp.tar.zst

      - save_cache:
          key: v1-incomplete-{{ epoch }}
          paths:
            - /home/circleci/aosp.tar.zst
