# https://github.com/Un1Gfn/avx/blob/master/.circleci/config.yml

# /exp01/config.yml
# /exp02/config.yml
# /.circleci/config.yml

version: 2

jobs:

  build:

    # https://circleci.com/docs/2.0/configuration-reference/#branches
    branches:
      only:
        - download
        - build-A
        - build-B
        # - placeholder

    # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
    # Xenial Xerus
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false

    resource_class: medium

    steps:

      # - run:
      #     name: Check if SSH is running
      #     command: |
      #       sudo -i pgrep -a sshd
      #       [ -n "$(sudo -i pgrep -a sshd)" ] || exit 1

      - run:
          name: "Remove bloat"
          working_directory: /opt/
          command: |
            sudo rm -rf firefox
            sudo rm -rf google/chrome
            sudo rmdir google
            sudo rm -rf circleci/.nvm
            sudo rm -rf circleci/.rvm
            sudo rm -rf circleci/.pyenv
            sudo rmdir circleci
            sudo rm -rf containerd

      - run:
          name: "BASH_ENV"
          command: |
            cat <<"EOF" >"$BASH_ENV"
            #
            export apt="sudo -i apt-get -q --allow-downgrades --allow-remove-essential --allow-change-held-packages --allow-unauthenticated"
            # export apt="sudo -i apt-get -q --allow-downgrades --allow-remove-essential --allow-change-held-packages"
            #
            export PROJ_DIR="/root/project"
            export _JAVA_OPTIONS="-Xmx$RAM"
            #
            EOF
            source "$BASH_ENV"

      # https://packages.ubuntu.com/
      # git repo time inetutils rxvt-unicode-terminfo openssh sudo
      # wget tree nano vim pv xz unzip
      # https://source.android.com/setup/build/initializing#installing-required-packages-ubuntu-1404
      # https://android.googlesource.com/platform/build/+/master/tools/docker/Dockerfile
      - run:
          name: "APT init"
          command: |
            sudo -i apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
            sudo -i apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5DC22404A6F9F1CA
            $apt update
            $apt autoremove --purge

      # https://unix.stackexchange.com/questions/410579/change-the-python3-default-version-in-ubuntu
      # https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
      - run:
          name: "Kill python* and get deadsnakes/python3.6"
          command: |
            # 
            sudo -i add-apt-repository -y ppa:deadsnakes/ppa # Depends on python(3?)
            # 
            rm -rf /opt/circleci/.pyenv || true
            for py in \
              python{,2{,.7},3{,.5}}{,-minimal} \
              libpython{,2{,.7},3{,.5}}{-stdlib,-minimal}
            do
              $apt purge "$py" || true
            done
            $apt autoremove --purge
            # 
            sh -c "python  --version" && exit 1
            sh -c "python2 --version" && exit 1
            sh -c "python3 --version" && exit 1
            [ -z "$(dpkg -l | grep python)" ] || exit 1
            # 
            $apt update
            $apt install python3.6
            hash -r
            sudo -i update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
            sudo -i update-alternatives --install /usr/bin/python  python  /usr/bin/python3.6 1
            sudo -i update-alternatives --set python3 /usr/bin/python3.6
            sudo -i update-alternatives --set python  /usr/bin/python3.6
            hash -r
            python  --version | grep -Fe 'Python 3.6' || exit 1
            python3 --version | grep -Fe 'Python 3.6' || exit 1

      - run:
          name: "Install repo"
          command: |
            install -m755 /dev/null ~/bin/test2
            cat <<"---" >~/bin/test2
              #!/bin/bash
              echo $((740+37))
            ---
            test2
            rm -v ~/bin/test2
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            file ~/bin/repo
            ls -l ~/bin/repo
            gpg --recv-key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
            curl https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ~/bin/repo
            hash -r

      - run:
          name: "AOSP dir"
          command: mkdir -v /home/circleci/aosp

      - run:
          name: "[A] Disk usage (approx 5G)"
          command: |
            echo
            sudo -i df -h
            echo
            echo

      # https://gist.github.com/earthgecko/3089509
      # https://superuser.com/questions/603547/how-can-i-limit-the-size-of-the-android-source-i-need-to-download-with-repo-syn
      # https://source.android.com/setup/develop/repo
      # https://source.android.com/setup/start/build-numbers#source-code-tags-and-builds
      # https://stackoverflow.com/a/19636869
      #                     fetch   04:39.59   .repo/ 156M
      #       update working tree   27:01.87   .repo/  13G   ~/aosp/ 43G
      #     extract .repo w/ sync   10:34.70   .repo/  13G   ~/aosp/ 43G
      - run:
          name: "Download AOSP"
          no_output_timeout: 1h
          working_directory: /home/circleci/aosp/
          command: |
            function A {
              [ "$#" -ne 1 ] && set -- 1
              cat /dev/urandom | tr -dc    'A-Z' | fold -w "$1" | head -n 1
            }
            function a {
              [ "$#" -ne 1 ] && set -- 1
              cat /dev/urandom | tr -dc    'a-z' | fold -w "$1" | head -n 1
            }
            function x {
              [ "$#" -ne 1 ] && set -- 1
              cat /dev/urandom | tr -dc 'a-z0-9' | fold -w "$1" | head -n 1
            }
            git config --global user.email "$(a)$(x 10)@$(a 5).org"
            git config --global user.name "$(A)$(a 5) $(A)$(a)"
            unset -f A
            unset -f a
            unset -f x
            cat ~/.gitconfig
            echo
            yes | repo init -u https://android.googlesource.com/platform/manifest -b android-8.1.0_r52 -c --depth=1 --no-clone-bundle --partial-clone  || true
            echo
            free -h
            echo
            sudo -i sync
            echo 3 | sudo tee /proc/sys/vm/drop_caches
            free -h
            echo
            [ "$(nproc --all)" -eq 2 ] || exit
            /usr/bin/time --format="\n  wall clock time - %E\n" repo sync -c -q -j2
            echo
            echo

      - run:
          name: "[B] Disk usage (approx 5G+15G+30G)"
          command: |
            echo
            sudo -i df -h
            echo
            echo

      - run:
          name: "Remove .repo"
          working_directory: /home/circleci/aosp/
          command: |
            rm -rf .repo

      - run:
          name: "[C] Disk usage (approx 5G+30G)"
          command: |
            echo
            sudo -i df -h
            echo
            echo

      - run:
          name: "Zstd"
          no_output_timeout: 1h
          command: tar -c --zstd -f aosp.tar.zst aosp/

      - run:
          name: "[D] Disk usage (approx 5G+30G+?G)"
          command: |
            echo
            sudo -i df -h
            echo
            echo

      - save_cache:
          key: v1-tree-{{ epoch }}
          paths:
            - /home/circleci/aosp.tar.zst

      # - run:
      #     name: "Wait for SSH"
      #     when: always
      #     command: |
      #       echo
      #       i=0
      #       while true; do
      #         sleep 60
      #         i=$((i+1))
      #         echo "$i min"
      #       done
      #       /usr/bin/false
